# Generated by Django 5.2.7 on 2025-10-23 15:10

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("text", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
                "default_related_name": "categories",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("business", "Бизнес"),
                            ("personal", "Личное"),
                            ("tax", "Налог"),
                        ],
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "статус транзакции",
                "verbose_name_plural": "Статусы транзакции",
                "ordering": ("name",),
                "default_related_name": "statuses",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("refill", "Пополнение"), ("withdrawals", "Списание")],
                        max_length=11,
                    ),
                ),
            ],
            options={
                "verbose_name": "тип транзакции",
                "verbose_name_plural": "Типы транзакции",
                "ordering": ("name",),
                "default_related_name": "types",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("text", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "Подкатегории",
                "ordering": ("name",),
                "default_related_name": "sub_categories",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "category",
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field="type",
                        chained_model_field="type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.status",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "sub_categories",
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field="category",
                        chained_model_field="category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.subcategory",
                        verbose_name="Подкатегории",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.type",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись о ДДС",
                "verbose_name_plural": "Записи о ДДС",
                "ordering": ["created"],
                "default_related_name": "transactions",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="money.type",
                verbose_name="Тип транзакции",
            ),
        ),
    ]
